import React,{useEffect,useMemo,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {useLanyard} from "use-lanyard";
import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import {RowsPhotoAlbum} from "react-photo-album";
import "react-photo-album/rows.css";
import {Doughnut} from "react-chartjs-2";
import {ArcElement,Chart as ChartJS,Tooltip} from "chart.js";
import {config} from "./config";
import "./styles.css";

ChartJS.register(ArcElement,Tooltip);
const safeJSON=(value,fallback=null)=>{if(!value)return fallback;if(typeof value==="object")return value;try{return JSON.parse(value)}catch{return fallback}};
const CardHead=({title,meta})=><div className="card-head"><span>{title}</span><small>{meta}</small></div>;
const Empty=({label,detail})=><div className="empty"><strong>{label}</strong><span>{detail}</span></div>;

function MapCard(){const ref=useRef(null);useEffect(()=>{if(!ref.current)return;const map=new maplibregl.Map({container:ref.current,style:"https://tiles.openfreemap.org/styles/dark",center:[config.lng,config.lat],zoom:8.4,attributionControl:false,interactive:false});map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");const el=document.createElement("div");el.className="map-avatar";el.innerHTML='<img src="https://ruoli-presence-live-mzi3pei9e-musdkar-6224.vercel.app/avatar.webp" alt="avatar">';new maplibregl.Marker({element:el}).setLngLat([config.lng,config.lat]).addTo(map);return()=>map.remove()},[]);return <article className="card map-card"><div ref={ref} className="map-canvas"/><div className="map-shade"/><h2>{config.city}</h2><div className="map-pill">◎ {config.city}, {config.region} · city level</div></article>}

function WeatherCard(){const[weather,setWeather]=useState(null);useEffect(()=>{fetch(`https://api.open-meteo.com/v1/forecast?latitude=${config.lat}&longitude=${config.lng}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=${encodeURIComponent(config.timezone)}`).then(r=>r.json()).then(d=>setWeather(d.current||null)).catch(()=>setWeather(false))},[]);const names={0:"Clear",1:"Mostly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",51:"Drizzle",61:"Rain",63:"Rain",65:"Heavy rain",80:"Showers",95:"Thunderstorm"};return <article className="card weather-card"><CardHead title="Weather · Wuhan" meta="Open-Meteo"/><div className="weather-main"><div><strong>{weather&&weather.temperature_2m!=null?Math.round(weather.temperature_2m)+"°":"--°"}</strong><span>{weather?(names[weather.weather_code]||"Current weather"):weather===false?"unavailable":"loading…"}</span></div>{weather&&<small>feels {Math.round(weather.apparent_temperature)}°<br/>wind {Math.round(weather.wind_speed_10m)} km/h</small>}</div></article>}

function SoftwareCard({apps}){if(!apps?.length)return <article className="card apps-card"><CardHead title="Software / today" meta="ActivityWatch"/><Empty label="ActivityWatch not linked" detail="Run bridge/activitywatch_bridge.py"/></article>;const top=apps.slice(0,5),total=top.reduce((s,a)=>s+a.minutes,0)||1,colors=["#8e7cff","#70a7ff","#ed7997","#6fc9b3","#50545e"],data={labels:top.map(a=>a.name),datasets:[{data:top.map(a=>a.minutes),backgroundColor:colors,borderWidth:0}]};return <article className="card apps-card"><CardHead title="Software / today" meta="ActivityWatch"/><div className="apps-body"><div className="chart-wrap"><Doughnut data={data} options={{cutout:"72%",plugins:{legend:{display:false},tooltip:{enabled:true}},animation:false}}/></div><div className="usage-list">{top.map((a,i)=><div className="usage-row" key={a.name}><span>{a.name}</span><i><b style={{width:`${a.minutes/total*100}%`,background:colors[i]}}/></i><strong>{Math.round(a.minutes/total*100)}%</strong></div>)}</div></div></article>}

function KeyboardCard(){return <article className="card keyboard-card"><CardHead title="Keyboard / today" meta="WhatPulse"/>{config.whatPulseHeatmapUrl?<a className="heatmap-link" href={config.whatPulseProfileUrl||config.whatPulseHeatmapUrl} target="_blank" rel="noreferrer"><img src={config.whatPulseHeatmapUrl} alt="WhatPulse keyboard heatmap"/></a>:<Empty label="WhatPulse heatmap not linked" detail="Use WhatPulse → Input → Share/Post Online, then set VITE_WHATPULSE_HEATMAP_URL"/>}</article>}

function PhotosCard(){return <article className="card photos-card"><CardHead title="Photos / VRChat" meta="React Photo Album"/><div className="photo-album"><RowsPhotoAlbum photos={config.photos} targetRowHeight={220} spacing={6} padding={0}/></div></article>}

function FitnessCard({health}){if(!health)return <article className="card fitness-card"><CardHead title="Fitness" meta="Health Auto Export"/><Empty label="Health not linked" detail="POST Step Count / Heart Rate to /api/health"/></article>;return <article className="card fitness-card"><CardHead title="Fitness" meta="Health Auto Export"/><div className="fitness-content"><div className="fitness-ring"><span>◎</span></div><div><strong>{Number(health.steps||0).toLocaleString()}</strong><small>steps today</small>{health.heartRate&&<em>{Math.round(health.heartRate)} bpm</em>}</div></div></article>}

function DevicesCard(){return <article className="card devices-card"><CardHead title="Devices" meta="daily / play"/><div className="device-columns"><DeviceGroup title="daily" items={[["MacBook Pro · M1 Pro","macOS"],["iPhone 16 Pro Max","mobile"],["AirPods Pro 3","audio"]]}/><DeviceGroup title="play" items={[["Quest 3","VR"],["Gaming Laptop","7945HX · RTX 5070 Ti"],["Xiaomi Pad 7S Pro","tablet"]]}/></div></article>}
function DeviceGroup({title,items}){return <div><h4>{title}</h4>{items.map(([n,m])=><div className="device" key={n}><b>{n}</b><span>{m}</span></div>)}</div>}

function StatusCard({presence}){const status=presence?.discord_status||"offline",activity=presence?.activities?.find(a=>a.name&&!['Spotify'].includes(a.name));return <article className="card status-card"><CardHead title="Status" meta="Lanyard"/><div className="status-main"><span className={`status-dot ${status}`}/><strong>{status}</strong><small>{activity?.details||activity?.name||(presence?"Discord presence":"Lanyard not linked")}</small></div></article>}
function MusicCard({presence}){const s=presence?.spotify;return <article className="card music-card"><CardHead title="Currently listening" meta="Lanyard / Spotify"/>{s?<><img className="album-art" src={s.album_art_url} alt={s.album}/><div className="track-info"><strong>{s.song}</strong><span>{s.artist}</span></div></>:<Empty label="nothing playing" detail={presence?"Spotify is idle":"Set VITE_DISCORD_ID after joining Lanyard"}/>}</article>}
function VrcStatus({presence}){const vrc=presence?.activities?.find(a=>/vrchat/i.test(a.name||'')||/vrchat/i.test(a.details||''));return vrc?<div className="vrc-line">VRChat · {vrc.details||vrc.state||"active"}</div>:null}

function Shell({presence}){const apps=safeJSON(presence?.kv?.apps_today,null)?.apps||[],health=safeJSON(presence?.kv?.health_today,null),[now,setNow]=useState(new Date());useEffect(()=>{const t=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(t)},[]);const local=useMemo(()=>new Intl.DateTimeFormat('en-GB',{timeZone:config.timezone,hour:'2-digit',minute:'2-digit',hour12:false}).format(now),[now]);return <><header><div className="brand">RUOLI<b>.</b></div><nav><a href="#">Home</a><a href="#photos">Photos</a><a href="#uses">Uses</a><a href="#now">Now</a></nav><div className="edition">digital presence<br/>wuhan edition · 2026</div></header><main><aside><div className="sidebar"><div className="kicker">About me</div><div className="identity"><img className="avatar" src="https://ruoli-presence-live-mzi3pei9e-musdkar-6224.vercel.app/avatar.webp" alt="avatar"/><div><h1>mostly<br/><i>online.</i></h1><p>Student, developer and VR enthusiast. Mostly code, VRChat, music, hardware and whatever I am building next.</p></div></div><div className="rule"/><dl><div><dt>based in</dt><dd>Wuhan, China</dd></div><div><dt>local time</dt><dd>{local}</dd></div><div><dt>presence</dt><dd>● {presence?.discord_status||'not linked'}</dd></div></dl><VrcStatus presence={presence}/><div className="sidebar-note"><b>Existing wheels first.</b><br/>Presence by Lanyard, activity by ActivityWatch, health by Health Auto Export, input by WhatPulse.</div></div></aside><section className="content" id="now"><div className="grid"><StatusCard presence={presence}/><WeatherCard/><MapCard/><MusicCard presence={presence}/><PhotosCard/><FitnessCard health={health}/><DevicesCard/><SoftwareCard apps={apps}/><KeyboardCard/></div></section></main></>}
function LanyardApp(){const presence=useLanyard(config.discordId);return <Shell presence={presence}/>}
function App(){return config.discordId?<LanyardApp/>:<Shell presence={null}/>}
createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
